name: Test
on:
  pull_request:
  push: { branches: master }

jobs:
  test:
    name: Verify build
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Build docker image
      run: docker-compose build

    - name: Run test
      run: docker-compose run test
